version: '3.8'

services:
  # 1. Database Service (MariaDB)
  db:
    image: mariadb:10.11
    container_name: technime_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      # Mount volume untuk persistensi data db
      - db_data:/var/lib/mysql
      # Mount file SQL lokal agar ter-seeding secara otomatis saat pertama kali container dijalankan
      - ./webDinamis/db_data/uasadmin_2388010017.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - technime_net

  # 2. Web Application Service (PHP Apache - Dynamic Web)
  web-dinamis:
    image: muharifrizky0225pohv/uasdinamis:latest
    build:
      context: ./webDinamis
      dockerfile: Dockerfile
    container_name: technime_web_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - technime_net

  # 3. Static Web Service (Nginx - Static Web CV)
  web-statis:
    image: muharifrizky0225pohv/uasstatis:latest
    build:
      context: ./webStatis
      dockerfile: Dockerfile
    container_name: cv_statis_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./webStatis:/usr/share/nginx/html
    networks:
      - technime_net

volumes:
  db_data:

networks:
  technime_net:
    driver: bridge
